 create table library_profile(
           library_name varchar(100) primary key NOT NULL,
             address varchar(100),
              city varchar(50),
              state varchar(50),
              contact_person varchar(50),
              contact_no varchar(15),
              Email varchar(50),
              Website varchar(50),
              registration_no varchar(50),
          pan_no varchar(15),
          GST_no varchar(50),
          Bank_name varchar(50),
          Account_no varchar(50),
          IFSC_code varchar(15),
         UPI_ID varchar(30));